---
title: "Developing a Writing Plan"
format: html
toc: true
editor: source
---
## Session Overview

In this session, we'll initiate our seminar journal article writing workshop. We'll discuss your general feelings about writing, and will also share your article abstracts.

## Before we Meet

### Read

- Belcher Week 1: Designing Your Plan for Writing
- Belcher Week 2: Starting Your Article

### Write
- Complete your Week 1 [Calendar for Planned (Not Actual) Time Spent Writing](01_introduction/Belcher-Week-1-Calendar-for-Actual-Not-Planned-Time-Spent-Writing-This-Week.pdf)
- Complete your first and second entries in your [Twelve-Week Calendar for Planning Article Writing Schedule](01_introduction/Belcher-Twelve-Week-Calendar-for-Planning-Article-Writing-Schedule.pdf)
- Complete your article abstract.

### Reflect

- What is your typical experience of writing?
- What are your negative feelings about writing?
- What lessons have you learned about your positive experiences of writing?
- What text are you planning to work up over the course of the semester?
- Where's your typical writing space?
- What writing rituals do you observe?

## After we Meet

## Resources
