---
title: "Targeting a Journal"
format: html
toc: true
editor: source
---
## Session Overview

This session will focus on identifying a publication strategy for your work based upon the type of argument you seek to make and the prospective audience for which your work will be in touch with. At first, it can be overwhelming to do this identification. We'll talk through various tools and strategies which can help you develop a short list of 3-5 target journals as well as a preferred submission order for those journals.

## Before we Meet

### Read
- Belcher Week 3: Advancing Your Argument
- Belcher Week 4: Selecting a Journal

### Write
- Write a statement of the argument of your article as you currently understand it.
- Have someone review your abstract.
- Revise your argument and bring both your original and revised statement to of argument to our class session.

### Research
- Identify 5 journals you know of that might be suitable for your article. Rank them by preferred order of submission.
- Write a draft inquiry to the managing editor of the journal regarding your prospective article (you need not send this to them yet).

## After we Meet

## Additional Resources
