---
title: "Ph.D. Showcase"
format: html
toc: true
editor: source
---
## Session Overview

On Friday 9/22 DSUP will host the Ph.D. Research Showcase in Architecture Building Room 210a (608 Lorado Taft Dr, Champaign, IL 61820).

New for this year, DSUP has requested that faculty participate by sharing a brief update on their research interests and updates on their courses, program milestones, and academic/professional development. Food will be provided.   

All doctoral students and faculty are expected to present for five 5 minutes.  

This email includes instructions and suggestions to prepare your presentation for the DSUP Showcase as well as a Google Form that requests your availability for specific time slots.  

By Sept. 15, please complete the [Google Form](https://forms.gle/NxWcoz4qzgh9mVMV6) indicating if you are attending the DSUP Showcase, when you are NOT available during the DSUP Showcase, and if you have any dietary restrictions. 

After everyone completes the Google Forms, we will assign everyone a time slot and email out the final event schedule.

Second, prepare to speak for five minutes (or less) with one to three slides about where you graduated, how long you’ve been here, your research interests, courses you teach, and any other personal or professional achievements. 
Please upload your slides to this [Box Folder](https://uofi.app.box.com/folder/225448700829) by Sept. 21. 

## Before we Meet

## After we Meet

## Additional Resources
