---
title: "ACSP Conference"
format: html
toc: true
editor: source
---
## Session Description
The ACSP Annual Meeting will be taking place this week - since many in our community will be attending the conference, we will not hold a seminar session this week.

## Presentations featuring Planning at Illinois Students and Faculty

### COMMUNITY ORGANIZING AND MOVEMENTS FOR SOCIAL AND ECONOMIC EQUALITY
LEE, Kevin, moderator
DOUSSARD, Marc
KIM, Anna
SARMIENTO, Carolina

### VIRAL CASH: PANDEMIC AND THE DIFFUSION OF BASIC INCOME TRIALS
DOUSSARD, Marc

### INTEGRATION OR PRECARIZATION? REFUGEE LABOR IN A SEGMENTED LABOR MARKET IN GERMANY
YENIGUN, Ozge

### POLICYMAKING FOR COMMUNITY RELOCATION IN PUERTO RICO AFTER 2017 HURRICANE MARIA
OLSHANSKY, Robert
GARCIA, Ivis

### A SEQUENCE-BASED ANALYSIS OF FEDERAL HOUSING ASSISTANCE PARTICIPATION
GREENLEE, Andrew
MCCLURE, Kirk

### LEARNING TO HAVE DIFFICULT CONVERSATIONS IN A DIVIDED GLOBAL CONTEXT
PENDALL, Rolf, moderator
HU, Lingqian
SHI, Linda
RUKMANA, Deden
GREENLEE, Andrew
ZHANG, Ming
TEWARI, Meenu
DAS, Ashok

### “WE WERE FORCED TO LEAVE OUR TOWN, BUT OUR TOWN NEVER LEFT US”: USING ARTS-BASED METHODS AND RADICAL SOCIAL CARTOGRAPHY AS REPARATION IN PRESERVATION PLANNING IN CHILE
NOVOA, Magdalena

### BED BUG INFESTATION IN SUBSIDIZED HOUSING: RETHINKING PLANNING FROM THE ENTANGLEMENT OF HUMANS AND INSECTS
BASNET, Vinisha

### AFTER THE MINIMUM PARKING REQUIREMENT: PARKING REFORM IN A SMALL CITY
SOHONI, Srirang
LEE, Bumsoo

### EQUITY PLANNING FOR A FUTURE WITH CONNECTED AND AUTONOMOUS VEHICLES: REDEFINING READINESS MEASURES AND METHODS
BENKRAOUDA, Ouafa
CHAKRABORTY, Arnab

### WHAT HAPPENS AFTER THE CRASH? EQUITY IN PLANNERS’ RESPONSE TO PEDESTRIAN AND BICYCLE CRASHES THROUGH INFRASTRUCTURE INTERVENTIONS
BRAUN, Lindsay
LEE, Kyuhyun
MERCK, Amanda

### PLANNING FOR SPATIAL JUSTICE IN SOUTH AFRICA: LESSONS FOR THE U.S.?
PENDALL, Rolf

### IS 'JUST GREEN ENOUGH' ENOUGH? SUCCESSES AND FAILURES OF ANTI-GENTRIFICATION PARK PLANNING IN MINNEAPOLIS
WALKER, Rebecca
RAMER, Hannah

### TAUGHT IN AMERICA II: CROSS-BORDER AND MULTICULTURAL LEARNING THROUGH A COSMOPOLITAN EDUCATION IN PLANNING
CHIU-SHEE, Colleen
SHI, Linda

### EQUITY THROUGH WATER: A COMMUNITY-BASED PARTICIPATORY MODEL
PEREZ, Omar